displayName: 스마일게이트 - 인프라 자산 검색 에이전트
schemaName: cr488_agentitGLqI
accessControlPolicy: GroupMembership
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  settings:
    GenerativeActionsEnabled: true

  isAgentConnectable: true
  gPTSettings:
    defaultSchemaName: cr488_agentitGLqI.gpt.default

  aISettings:
    useModelKnowledge: true
    isFileAnalysisEnabled: true
    isSemanticSearchEnabled: true
    optInUseLatestModels: false

  recognizer:
    kind: GenerativeAIRecognizer

template: default-2.1.0
language: 1042